/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/CoreBGS-final2.glb -o ./src/app/team/domain/core-team/CoreTeamScene.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CoreTeamScene(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/CoreBGS-final2.glb')
  const { actions } = useAnimations(animations, group)

  console.log("ANIMATIONS:", animations);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Object_13001" geometry={nodes.Object_13001.geometry} material={materials['Scene_-_Root.001']} position={[0, 1.59, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[1.13, 1.505, 1.13]} />
        <mesh name="Object_13006" geometry={nodes.Object_13006.geometry} material={materials['Scene_-_Root.001']} position={[-3, 1.59, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[1.13, 1.505, 1.13]} />
        <mesh name="Object_13007" geometry={nodes.Object_13007.geometry} material={materials['Scene_-_Root.001']} position={[-6, 1.59, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[1.13, 1.505, 1.13]} />
        <mesh name="Object_13008" geometry={nodes.Object_13008.geometry} material={materials['Scene_-_Root.001']} position={[3, 1.59, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[1.13, 1.505, 1.13]} />
        <mesh name="Object_13009" geometry={nodes.Object_13009.geometry} material={materials['Scene_-_Root.001']} position={[6, 1.59, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[1.13, 1.505, 1.13]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.004']} position={[-0.022, 0.357, -0.003]} scale={[9.805, 0.141, 9.805]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} position={[0, 0.247, -3.359]} scale={[20.489, 1, 8.93]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[-0.022, 0.357, -0.003]} scale={[9.805, 0.141, 9.805]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.016']} position={[0, 3.182, -2.488]} scale={[0.356, 0.409, 0.867]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.014']} position={[6, 3.182, -2.488]} scale={[0.356, 0.409, 0.867]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.015']} position={[3, 3.182, -2.488]} scale={[0.356, 0.409, 0.867]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.017']} position={[-6, 3.182, -2.488]} scale={[0.356, 0.409, 0.867]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.001']} position={[-3, 3.221, -2.488]} scale={[0.356, 0.409, 0.867]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/CoreBGS-final2.glb')
