/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/path.glb -o ./src/app/about/AboutDoor.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AboutDoor(props) {
  const { nodes, materials } = useGLTF('/models/path.glb')
  return (
    <group {...props} dispose={null}>
      <axesHelper args={[5]} />
      <ambientLight intensity={5} />
      <mesh geometry={nodes.Cube010_Material013_0001.geometry} material={materials['Material.013']} position={[0.451, 8.178, 151.114]} rotation={[-Math.PI / 2, 0, 1.568]} scale={[-5.799, -5.775, -1.401]} />
    </group>
  )
}

useGLTF.preload('/models/path.glb')
