/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/lantian_gate.glb -o ./src/app/about/LantainPortal.jsx 
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lantian-gate-9bdb6fe8f3624f2fa94f13c7e3080848
Title: Lantian Gate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LantainGate(props) {
  const { nodes, materials } = useGLTF('/models/lantian_gate.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group position={[82321.406, 247450.016, 160507.484]} rotation={[0, 0, -Math.PI / 2]} scale={1.27}>
            <mesh geometry={nodes.Stargate_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.Stargate_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID552_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID552_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID567_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID567_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID577_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID577_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID587_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID587_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID599_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID599_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID609_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID609_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID619_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID619_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID629_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID629_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID639_material_2_0.geometry} material={materials.material_2} />
            <mesh geometry={nodes.ID639_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID654_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID654_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID664_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID664_material_0.geometry} material={materials.material} />
            <mesh geometry={nodes.ID674_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID686_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID686_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID696_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID706_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID706_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID716_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID726_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID736_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID746_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID746_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID756_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID756_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID766_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID774_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID774_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID784_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID794_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID794_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID804_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID814_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID822_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID832_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID840_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID850_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID850_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID860_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID860_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID870_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID880_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID880_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID890_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID900_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID900_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID910_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID918_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID928_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID928_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID938_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID948_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID948_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID958_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID966_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID976_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID984_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID994_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID994_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1004_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID1004_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1014_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1024_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID1032_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1042_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID1042_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1052_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID1052_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1062_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1072_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID1072_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1082_Object__Beige_1_0.geometry} material={materials.Object__Beige_1} />
            <mesh geometry={nodes.ID1090_stargate2_0.geometry} material={materials.stargate2} />
            <mesh geometry={nodes.ID1100_stargate2x01_0.geometry} material={materials.stargate2x01} />
            <mesh geometry={nodes.ID1100_stargate2_0.geometry} material={materials.stargate2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/lantian_gate.glb')
