import './globals.css'
import { Jura } from 'next/font/google'
import { Providers } from './providers'

const jura = Jura({ subsets: ['latin'] })

export const metadata = {
  title: 'MLSC VIT Pune',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={jura.className}>    
      <Providers>
        {children}
      </Providers></body>

    </html>
  )
}
