/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/MLSC_text.glb -o ./src/app/components-3d/MLSCText.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MLSCText(props) {
  const { nodes, materials } = useGLTF('/models/MLSC_text.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Text.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/MLSC_text.glb')
