/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/final_domain_nav_platform2.glb -o src/app/team/MainPlatform.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MainPlatform(props) {
  const { nodes, materials } = useGLTF('/models/final_domain_nav_platform2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[2.573, 2.558, 4.578]}>
        <group position={[-4.948, -2.385, 9.885]} rotation={[0, 0, Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube004_emission_0_1.geometry} material={materials.emission} />
          <mesh castShadow receiveShadow geometry={nodes.Cube004_emission_0_2.geometry} material={materials['Material.007']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube004_emission_0_3.geometry} material={materials.material_0} />
        </group>
      </group>
      <group position={[-1.464, 5.079, 109.374]} rotation={[-Math.PI / 2, 0, 1.568]} scale={[-5.799, -11.55, -1.401]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube010_Material013_0.geometry} material={materials['Material.013']} position={[7.197, 0.175, -2.211]} scale={[1, 0.5, 1]} />
      </group>
      <group position={[-0.759, 7.59, 0.45]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[51.037, 51.037, 4.314]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_Material013_0.geometry} material={materials['Material.001']} position={[0, 0, -0.448]} />
      </group>
      <group position={[-0.807, 20.068, 0.479]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[9.174, 9.174, 4.731]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_Material001_0.geometry} material={materials['Material.002']} position={[0, 0, 0.086]} />
      </group>
      <group position={[-0.807, 27.069, 0.479]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[8.655, 8.655, 1.109]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_Material013_0.geometry} material={materials['Material.001']} position={[0, 0, 0.397]} />
      </group>
      <group position={[-0.807, 20.068, 0.479]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[9.174, 9.174, 4.731]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003__0.geometry} material={materials['Cylinder.003__0']} position={[0, 0, 0.194]} />
      </group>
      <group position={[-0.807, 27.069, 0.479]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[8.655, 8.655, 1.109]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder004__0.geometry} material={materials['Cylinder.003__0']} position={[0, 0, 0.478]} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_Material013_0.geometry} material={materials['Material.013']} position={[-1.569, 12.481, 48.354]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[51.037, 51.037, 4.314]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder008_Material013_0.geometry} material={materials['Material.013']} position={[-1.569, 12.481, 48.354]} rotation={[-Math.PI / 2, 0, -0.788]} scale={[51.037, 51.037, 4.314]} />
    </group>
  )
}

useGLTF.preload('/models/final_domain_nav_platform2.glb')
