/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/tri-portal.glb -o src/app/team/Components/Portalmodel.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function PortalModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/tri-portal.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="eb5aeda8010a4781bcb9285ea743a8c6fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Portal" position={[0, 0.704, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials.Portal_Inner} />
                  <mesh name="1" geometry={nodes['1'].geometry} material={materials.Portal_Rim} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tri-portal.glb')
