/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/domain-names/ai-mldcurvedtext.glb -o ./src/app/team/domain/ai-ml/AIMLTextModel.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Text3DModel(props) {
  const { nodes, materials } = useGLTF('/models/domain-names/ai-mldcurvedtext.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0, 1.338, 0]} rotation={[Math.PI / 2, 0, 2.943]} scale={5.731} />
    </group>
  )
}

useGLTF.preload('/models/domain-names/ai-mldcurvedtext.glb')
